### ISSUE TITLE
Make altering the menu via JS easier

### ISSUE THREAD

**Issue by mrclay** [ColdTrick/lazy_hover#7]
Now that the menus can arrive at any time, this makes it difficult to reliably alter the menu via JS. (In my case I need to make a backend call to CometChat to see if the user is online and if so alter an item.)

It would be handy to have a hook fire when the menu was added to the DOM. Ideally the hook would also receive the GUID of the user.

**Comment by jdalsem** [comment]
Closing this as core now delivers the hover menu via ajax, which makes this plugin obsolete
